#!/usr/bin/env zsh

# vim:filetype=zsh syntax=zsh tabstop=2 shiftwidth=2 softtabstop=2 expandtab autoindent fileencoding=utf-8

# git command: st

# Source shell helpers if they aren't already loaded
# Faster than 'type is_shellrc_sourced &>/dev/null': no subshell, pure zsh builtin check.
(( $+functions[is_shellrc_sourced] )) || source "${HOME}/.shellrc"

# Note: Use a function so that it can accept parameters
st() {
  local folder
  local -a switches
  for arg in "$@"; do
    if [[ "${arg}" == --* ]]; then
      switches+=("${arg}")
    elif is_zero_string "${folder}"; then
      folder="${arg}"
    fi
  done
  folder="${folder:-$(pwd)}"
  section_header2 "$(yellow 'Checking') $(purple "${folder}")"
  if ! is_git_repo "${folder}"; then
    warn "Skipping finding status of the repo since '$(yellow "${folder}")' doesn't exist or is not a git repo"
  else
    git -C "${folder}" st "${switches[@]}"
  fi
}

st "$@"
compdef st
